# Generated by Django 3.2.3 on 2021-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerfeatures',
            name='species',
            field=models.TextField(default='', max_length=10),
        ),
    ]
